### ISSUE TITLE
Video file to image stream

### ISSUE THREAD

**Issue by jacobggman** [animeng/flutter_export_video_frame#2]
Hi! I have a video file in my assets folder (like mp4). I want to read that video file as an image stream, like an image stream in the camera package https://pub.dev/documentation/camera/latest/camera/CameraController/startImageStream.html

I want to pass the image to Tflite model.

Something like that:
```
controller = loadVideo('assets/example.mp4');  // How to do that?
controller.startImageStream((CameraImage img) {
          Tflite.runPoseNetOnFrame(
              bytesList: img.planes.map((plane) {
                return plane.bytes;
              }).toList(),
              imageHeight: img.height,
              imageWidth: img.width,
              numResults: 1,
              threshold: 0.1,
            ).then((recognitions) {
              // ...
            }
        }
```

Basically read the video file asynchronous and get the image data.

Does your package support this? Do you know any package that can do that? How hard it will be to implement this in this package? Does this idea fit this package?

Thanks in advance!

**Comment by animeng** [comment]
It can be changed based on the package and implement this. Not difficult

**Comment by jtmuller5** [comment]
I'd definitely be interested in using this feature! Any idea when it will be added?

**Comment by jacobggman** [comment]
@animeng Can I implement is and make PR? It is fine if add the package `media_info` to implement this?

**Comment by animeng** [comment]
> @animeng Can I implement is and make PR? It is fine if add the package `media_info` to implement this?

Sure，if you can implement the feature  and test is ok. I will merge your PR.
