### ISSUE TITLE
Null pointer exception

### ISSUE THREAD

**Issue by yostrokon** [animeng/flutter_export_video_frame#3]
Trying to integrate. On ios works fine, with android getting this exception on cleanImageCache

Unhandled Exception: PlatformException(error, Attempt to invoke virtual method 'int android.content.Context.checkPermission(java.lang.String, int, int)' on a null object reference, null, java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.Context.checkPermission(java.lang.String, int, int)' on a null object reference
E/flutter (29239): 	at androidx.core.content.ContextCompat.checkSelfPermission(ContextCompat.java:538)
E/flutter (29239): 	at com.mengtnt.export_video_frame.PermissionManager.isPermissionGranted(PermissionManager.java:53)
E/flutter (29239): 	at com.mengtnt.export_video_frame.ExportVideoFramePlugin.onMethodCall(ExportVideoFramePlugin.java:65)
E/flutter (29239): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)

**Comment by animeng** [comment]
You can look up the PR: https://github.com/animeng/flutter_export_video_frame/pull/4#issuecomment-814639121

**Comment by courtneypresto** [comment]
Can you publish this as an official version please! 🙏🏻🙏🏻

**Comment by animeng** [comment]
> Can you publish this as an official version please! 🙏🏻🙏🏻

done
